#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx pretty-quick --pattern "apps/**/*.*(ts|json|html|scss)" --staged  && npx stylelint "apps/**/*.scss" --fix && nx run-many affected --all --target=lint --fix --uncommitted
